### ISSUE TITLE
add fast-clone

### ISSUE THREAD

**Issue by abenhamdine** [ahmadnassri/node-clone-benchmark#86]
Hi, and thx for this very useful project !

I was wondering : searching for the fastest clone method, I found out [fast-clone](https://github.com/codeandcats/fast-clone) wich claims to be 2x~3x faster than lodash.cloneDeep.
So would it be possible to add it to the benchmark ?

Thx in advance.

**Comment by ahmadnassri** [comment]
sure

**Comment by abenhamdine** [comment]
thx Ahmad !

**Comment by ahmadnassri** [comment]
@abenhamdine done! sadly `fast-clone` is not even close! :smile:
